version: '3'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5470:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: bd2@bd2.com
      PGADMIN_DEFAULT_PASSWORD: bd2
    ports:
      - "7070:80"
