version: '3.1'

services:

  mongo:
    container_name: mongo-5.0_db
    image: mongo:5.0.3
    ports:
      - 27000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: masterkey

  mongo-express:
    depends_on:
        - mongo
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: masterkey
      ME_CONFIG_MONGODB_URL: mongodb://root:masterkey@mongo:27017/

