version: '3.2'

services:
   db:
      image: mysql:8.0
      ports:
       - '6603:3306'
      environment:
        MYSQL_ROOT_PASSWORD: bd2

   app:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      ports:
        - '6060:80'
      environment:
        PMA_HOST: db